name: Pages Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install and Build Docs
        run: |
          npm ci
          npm run docs

      - name: Prevent Jekyll
        run: touch ./docs/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
